version: 2.1
jobs:
  build_tests:
    docker:
      - image: circleci/node:12
    steps:
      -checkout
      -run:
          name: Install npm dependencies
          command: |
            npm install --save 
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t reactjswebapp1 -t zoco1206/reactjswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u zoco1206 --password-stdin
            docker push zoco1206/reactjswebapp1:latest
workflows:
  build_test:
    jobs:
      - build_tests
      - build_docker_image
      
